perf: instead of git fetch origin we have shifted to git pull upstream

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,7 +43,7 @@ jobs:
 
               echo '⬇️ Pull latest code...'
               cd apps/custom_hrms
-              git fetch origin version-16 && git reset --hard origin/version-16 || { echo '❌ Git pull failed'; exit 1; }
+              git pull upstream version-16 || { echo '❌ Git pull failed'; exit 1; }
               cd \"$BENCH_DIR\"
 
               echo '⚙️ Run migrations...'
